- name: Launch proxy container
  community.docker.docker_container:
    name: my-httpd
    image: emilez10/tp-devops-httpd:latest
    networks:
      - name: frontend-network
    ports:
      - "80:80"
    env:
      BACKEND_HOST: "{{ backend_host }}"
      BACKEND_PORT: "{{ backend_port }}"
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python
