- name: Launch app container
  community.docker.docker_container:
    name: backend
    image: emilez10/tp-devops-simple-api:latest
    networks:
      - name: frontend-network
      - name: backend-network
    env:
      POSTGRES_DB: "{{ postgres_db }}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}" 
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python
